### ISSUE TITLE
How to determine if GPU is utilized or not

### ISSUE THREAD

**Issue by kyuhyong** [Tossy0423/yolov4-for-darknet_ros#14]
Hello, 
Thanks for combining all the stuffs for running yolo-v4 for ROS.

I was finally able to run YOLO with a webcam.

![Screenshot from 2021-08-20 16-16-50](https://user-images.githubusercontent.com/22294429/130195421-6bc1fe29-a335-4e52-b0b7-ab1a288392bb.png)

Resulting FPS I got is aroung 13.0~14.0 from my laptop running Intel Core i7-9750 with RTX2060.
Just wonder if GPU is running or not because I didn't change anything about the Makefile under darknet.
Is there a way to check whether the GPU is utilized?

**Comment by wwh01875** [comment]
You can run the $nvidia-smi command after executing the program to see if the gpu is used again
